### ISSUE TITLE
Fix parser

### ISSUE THREAD

**Issue by ethansocal** [what-the-python/wtpython#83]
Using no arguments results in wtpython opening with an index error. Putting a script name that doesn't exist results in wtpython opening with a FileNotFoundError. Also, the help popup no longer shows the script argument.

**Comment by mustafaquraish** [comment]
Fixing the `FileNotFoundError` is kind of annoying the way the arguments are parsed now. I have the following proposal:

- We add back `script` as a positional argument into the argument parser
- Use this to check if the script exists, otherwise give an appropriate error
- Then manually add the script name into `sys.argv` when we are running the code (for sake of correctness).

So something along the lines of:

```py
parser = argparse.ArgumentParser(...)
parser.add_argument('script', help='script name')
...
flags, rest = parser.parse_known_args()

...

if not os.path.isfile(flags['script']):
    exit(1)
 
...
sys.argv = [flags['script'], *rest] 
runpy.run_path(flags['script'])
```

@briancohan You were last were on this, thoughts?
